# Generated by Django 5.0.4 on 2024-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='medical_history',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='checkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
