# Generated by Django 5.0.4 on 2024-04-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_about_profile_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checkedin',
            field=models.DateField(),
        ),
    ]
