# Generated by Django 5.0.4 on 2024-04-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='medical_history',
            new_name='medications',
        ),
    ]
